name: MasterDeployCI
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install Packages
        run: npm install
      - name: Deploy to GH Pages
        run: |
          git config --global user.email "daffaputradamar@gmail.com"
          git config --global user.name "daffaputradamar"
          git remote set-url origin https://0fe779d788f4ba1f514186de15074e336258892c@github.com/daffaputradamar/WebFramework.git
          npm run deploy
